// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/freekieb7/smauth/internal/account"

type AppProps struct {
	RootProps RootProps
	User      account.User
	PageTitle string
}

func App(props AppProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container-fluid\" style=\"background: #F2F4F8; min-height: 100vh;\"><div class=\"row\"><!-- Sidebar --><nav class=\"col-md-3 col-lg-2 d-md-block sidebar collapse\" style=\"background: linear-gradient(180deg, #0B1962 0%, #05103A 100%); box-shadow: 2px 0 8px rgba(0,0,0,0.1); height: 100vh;\"><div class=\"d-flex flex-column h-100 pt-3\"><!-- Sidebar Header --><div class=\"sidebar-header p-3 border-bottom\" style=\"border-color: rgba(255,255,255,0.1) !important;\"><div class=\"d-flex align-items-center\"><div class=\"d-inline-flex align-items-center justify-content-center me-2\" style=\"width: 32px; height: 32px; background: #24E362; border-radius: 8px;\"><i class=\"bi bi-shield-lock text-white\"></i></div><h5 class=\"mb-0 text-white fw-bold\">SMAuth</h5></div></div><!-- User Info Section --><div class=\"p-3 border-bottom\" style=\"border-color: rgba(255,255,255,0.1) !important;\"><div class=\"d-flex align-items-center\"><div class=\"d-flex align-items-center justify-content-center me-3\" style=\"width: 36px; height: 36px; background: linear-gradient(135deg, #24E362 0%, #1bc956 100%); border-radius: 8px; font-weight: 600; font-size: 0.8rem; color: #064E3B;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(string(props.User.Email[0]))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 31, Col: 38}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div><div class=\"flex-grow-1 text-white\"><div style=\"font-size: 0.9rem; font-weight: 500;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 34, Col: 77}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div><div style=\"font-size: 0.75rem; color: rgba(255,255,255,0.7); text-transform: uppercase; letter-spacing: 0.5px;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Role.String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 35, Col: 148}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div></div></div><!-- Navigation Items - This will take up available space --><div class=\"flex-grow-1\" style=\"overflow-y: auto;\"><ul class=\"nav flex-column pt-3\"><!-- Dashboard (always visible) --><li class=\"nav-item mb-1\"><a class=\"nav-link text-white d-flex align-items-center px-3 py-2\" href=\"/dashboard\" style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-radius: 8px; margin: 0 12px; transition: all 0.2s ease;", templ.KV("background: rgba(36,227,98,0.2);", props.PageTitle == "Dashboard"), templ.KV("background: transparent;", props.PageTitle != "Dashboard"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 44, Col: 314}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\" onmouseover=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='rgba(36,227,98,0.1)'\" onmouseout=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='transparent'\"><i class=\"bi bi-house-door me-3\"></i> Dashboard</a></li><!-- Admin-only sections -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.Role == account.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<li class=\"nav-item mb-1\"><hr style=\"margin: 0.5rem 12px; border-color: rgba(255,255,255,0.1);\"></li><li class=\"nav-item mb-1\"><div class=\"text-white px-3\" style=\"font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; color: rgba(255,255,255,0.6); margin: 0 12px; font-weight: 600;\">Administration</div></li><li class=\"nav-item mb-1\"><a class=\"nav-link text-white d-flex align-items-center px-3 py-2\" href=\"/admin/users\" style=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-radius: 8px; margin: 0 12px; transition: all 0.2s ease;", templ.KV("background: rgba(36,227,98,0.2);", props.PageTitle == "Users"), templ.KV("background: transparent;", props.PageTitle != "Users"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 60, Col: 309}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\" onmouseover=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='rgba(36,227,98,0.1)'\" onmouseout=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='transparent'\"><i class=\"bi bi-people me-3\"></i> Users</a></li><li class=\"nav-item mb-1\"><a class=\"nav-link text-white d-flex align-items-center px-3 py-2\" href=\"/admin/clients\" style=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-radius: 8px; margin: 0 12px; transition: all 0.2s ease;", templ.KV("background: rgba(36,227,98,0.2);", props.PageTitle == "Clients"), templ.KV("background: transparent;", props.PageTitle != "Clients"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 66, Col: 315}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\" onmouseover=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='rgba(36,227,98,0.1)'\" onmouseout=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='transparent'\"><i class=\"bi bi-shield-lock me-3\"></i> Clients</a></li><li class=\"nav-item mb-1\"><a class=\"nav-link text-white d-flex align-items-center px-3 py-2\" href=\"/admin/resource-servers\" style=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var9 string
				templ_7745c5c3_Var9, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-radius: 8px; margin: 0 12px; transition: all 0.2s ease;", templ.KV("background: rgba(36,227,98,0.2);", props.PageTitle == "Resource Servers"), templ.KV("background: transparent;", props.PageTitle != "Resource Servers"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 72, Col: 342}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" onmouseover=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='rgba(36,227,98,0.1)'\" onmouseout=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='transparent'\"><i class=\"bi bi-server me-3\"></i> Resource Servers</a></li><li class=\"nav-item mb-1\"><a class=\"nav-link text-white d-flex align-items-center px-3 py-2\" href=\"/admin/audit-logs\" style=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var10 string
				templ_7745c5c3_Var10, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("border-radius: 8px; margin: 0 12px; transition: all 0.2s ease;", templ.KV("background: rgba(36,227,98,0.2);", props.PageTitle == "Audit Logs"), templ.KV("background: transparent;", props.PageTitle != "Audit Logs"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 78, Col: 324}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" onmouseover=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='rgba(36,227,98,0.1)'\" onmouseout=\"if (this.style.background !== 'rgba(36, 227, 98, 0.2)') this.style.background='transparent'\"><i class=\"bi bi-journal-text me-3\"></i> Audit Logs</a></li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</ul></div><!-- Logout Button at Bottom --><div class=\"mt-auto p-3 border-top\" style=\"border-color: rgba(255,255,255,0.1) !important;\"><button id=\"btn-logout\" type=\"button\" class=\"btn btn-sm w-100\" style=\"background: rgba(220, 38, 38, 0.1); color: #DC2626; border: 1px solid rgba(220, 38, 38, 0.3); border-radius: 6px; padding: 8px 16px; font-weight: 500; transition: all 0.2s ease;\" onmouseover=\"this.style.background='rgba(220, 38, 38, 0.2)'\" onmouseout=\"this.style.background='rgba(220, 38, 38, 0.1)'\"><i class=\"bi bi-box-arrow-right me-2\"></i>Sign Out</button></div></div></nav><!-- Main content --><main class=\"col-md-9 ms-sm-auto col-lg-10 px-md-4 py-4\"><div class=\"d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-3 mb-4\"><div class=\"d-flex align-items-center\"><div class=\"me-3\" style=\"width: 4px; height: 32px; background: #24E362; border-radius: 2px;\"></div><div><h1 class=\"h2 mb-0\" style=\"color: #0B1962; font-weight: 700;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(props.PageTitle)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/layout/app.templ`, Line: 100, Col: 87}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</h1><p class=\"text-muted mb-0\" style=\"font-size: 0.9rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.Role == account.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "Manage your healthcare authentication system")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "Welcome to your SMAuth dashboard")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</p></div></div></div><div class=\"main-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div></main></div></div><script>\n\t\t\tdocument.addEventListener(\"DOMContentLoaded\", function() {\n\t\t\t\tconst logoutButton = document.getElementById(\"btn-logout\");\n\t\t\t\tif (logoutButton) {\n\t\t\t\t\tlogoutButton.addEventListener(\"click\", async function() {\n\t\t\t\t\t\ttry {\n\t\t\t\t\t\t\t// Use different endpoints based on current path\n\t\t\t\t\t\t\tconst endpoint = window.location.pathname.startsWith('/admin') ? '/admin/signoff' : '/logout';\n\t\t\t\t\t\t\tconst response = await fetch(endpoint, {\n\t\t\t\t\t\t\t\tmethod: \"POST\",\n\t\t\t\t\t\t\t\theaders: {\n\t\t\t\t\t\t\t\t\t\"Content-Type\": \"application/json\",\n\t\t\t\t\t\t\t\t\t\"X-CSRF-Token\": document.querySelector('meta[name=\"csrf-token\"]').getAttribute(\"content\")\n\t\t\t\t\t\t\t\t}\n\t\t\t\t\t\t\t});\n\t\t\t\t\t\t\tif (response.ok) {\n\t\t\t\t\t\t\t\twindow.location.href = \"/login\";\n\t\t\t\t\t\t\t\treturn;\n\t\t\t\t\t\t\t} else {\n\t\t\t\t\t\t\t\talert(\"Sign out failed.\");\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t} catch (error) {\n\t\t\t\t\t\t\tconsole.error(\"Error during logout:\", error);\n\t\t\t\t\t\t\talert(\"Sign out failed.\");\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Root(props.RootProps).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
