// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/freekieb7/smauth/internal/audit"
	"github.com/freekieb7/smauth/internal/web/ui/template/component"
	"github.com/freekieb7/smauth/internal/web/ui/template/layout"
)

type AuditLogsProps struct {
	layout.AppProps
	LogEntries     []audit.LogEntry
	SuccessMessage string
	ErrorMessage   string
	Pagination     component.PaginationInfo
}

func AuditLogs(props AuditLogsProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Success/Error Messages --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.SuccessMessage != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"alert fade show mb-4\" role=\"alert\" style=\"background: linear-gradient(135deg, #F0FDF4 0%, #DCFCE7 100%); border: 1px solid #24E362; border-radius: 8px; color: #166534;\"><i class=\"bi bi-check-circle-fill me-2\" style=\"color: #24E362;\"></i> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.SuccessMessage)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 23, Col: 26}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " <button type=\"button\" class=\"btn-close float-end\" onclick=\"closeAlert(this)\" style=\"font-size: 0.75rem;\"></button></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.ErrorMessage != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"alert fade show mb-4\" role=\"alert\" style=\"background: linear-gradient(135deg, #FEF2F2 0%, #FEE2E2 100%); border: 1px solid #F87171; border-radius: 8px; color: #DC2626;\"><i class=\"bi bi-exclamation-triangle-fill me-2\" style=\"color: #EF4444;\"></i> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(props.ErrorMessage)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 30, Col: 24}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " <button type=\"button\" class=\"btn-close float-end\" onclick=\"closeAlert(this)\" style=\"font-size: 0.75rem;\"></button></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, " <div class=\"d-flex justify-content-between align-items-center mb-4\"><div><h1 style=\"color: #0B1962; font-weight: 700; font-size: 2rem;\">Audit Logs</h1><p style=\"color: #6B7280; margin-bottom: 0;\">View system activity and security events</p></div></div><!-- Audit Logs Table --> <div class=\"card border-0\" style=\"border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.05);\"><div class=\"card-body p-0\"><div class=\"table-responsive\"><table class=\"table table-hover mb-0\"><thead style=\"background: #F2F4F8; border-bottom: 2px solid #E5E7EB;\"><tr><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Timestamp</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Account ID</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Event</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Resource</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Action</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">Status</th><th style=\"color: #0B1962; font-weight: 600; padding: 8px 16px; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;\">IP Address</th></tr></thead> <tbody>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(props.LogEntries) == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<tr><td colspan=\"7\" class=\"text-center py-4\" style=\"color: #9CA3AF;\"><i class=\"bi bi-journal-text fs-1 d-block mb-2\" style=\"color: #D1D5DB;\"></i><div style=\"font-size: 1rem; font-weight: 500; margin-bottom: 4px;\">No audit logs found</div><div style=\"font-size: 0.875rem;\">System activity will appear here</div></td></tr>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				for _, entry := range props.LogEntries {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<tr style=\"border-bottom: 1px solid #F3F4F6;\"><td style=\"padding: 8px 16px;\"><div style=\"font-weight: 500; color: #374151; font-size: 0.85rem; font-family: 'SF Mono', 'Monaco', monospace;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(entry.CreatedAt.Format("2006-01-02 15:04:05"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 70, Col: 59}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></td><td style=\"padding: 8px 16px;\"><div style=\"font-weight: 600; color: #0B1962; font-size: 0.85rem; font-family: 'SF Mono', 'Monaco', monospace;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(entry.AccountID.String()[:8])
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 75, Col: 42}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "...</div></td><td style=\"padding: 8px 16px;\"><span style=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("padding: 4px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.3px;", templ.KV("background: #EBF8FF; color: #1E40AF;", entry.Event == "data_read"), templ.KV("background: #FEF3C7; color: #D97706;", entry.Event == "data_write"), templ.KV("background: #FEE2E2; color: #DC2626;", entry.Event == "data_delete"), templ.KV("background: #F0FDF4; color: #166534;", entry.Event == "auth_login"), templ.KV("background: #F3F4F6; color: #374151;", true))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 79, Col: 523}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(string(entry.Event))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 80, Col: 33}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</span></td><td style=\"padding: 8px 16px; color: #374151; font-weight: 500; font-size: 0.85rem;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(entry.Resource)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 83, Col: 111}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</td><td style=\"padding: 8px 16px; color: #374151; font-weight: 500; font-size: 0.85rem;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(entry.Action)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 84, Col: 109}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</td><td style=\"padding: 8px 16px;\"><span style=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 string
					templ_7745c5c3_Var11, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("padding: 4px 8px; border-radius: 4px; font-size: 0.7rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.3px;", templ.KV("background: #F0FDF4; color: #166534;", entry.Success), templ.KV("background: #FEF2F2; color: #DC2626;", !entry.Success))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 86, Col: 282}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					if entry.Success {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "Success")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					} else {
						templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "Failed")
						if templ_7745c5c3_Err != nil {
							return templ_7745c5c3_Err
						}
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</span></td><td style=\"padding: 8px 16px;\"><small style=\"color: #6B7280; font-family: 'SF Mono', 'Monaco', monospace; font-size: 0.75rem;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var12 string
					templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(entry.IPAddress.String())
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/audit_logs.templ`, Line: 95, Col: 133}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "</small></td></tr>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</tbody></table></div><!-- Pagination Controls -->")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = component.PaginationControls(props.Pagination).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</div></div><script>\n\t\t\t// Function to close alert and clear URL parameters\n\t\t\tfunction closeAlert(button) {\n\t\t\t\t// Remove the alert element\n\t\t\t\tbutton.parentElement.remove();\n\t\t\t\t\n\t\t\t\t// Clear URL parameters\n\t\t\t\tclearUrlParams();\n\t\t\t}\n\n\t\t\t// Function to clear error and success parameters from URL\n\t\t\tfunction clearUrlParams() {\n\t\t\t\tif (window.history && window.history.replaceState) {\n\t\t\t\t\tconst url = new URL(window.location);\n\t\t\t\t\turl.searchParams.delete('error');\n\t\t\t\t\turl.searchParams.delete('success');\n\t\t\t\t\twindow.history.replaceState(null, '', url);\n\t\t\t\t}\n\t\t\t}\n\n\t\t\t// Auto-clear URL parameters after showing the message (optional)\n\t\t\tdocument.addEventListener('DOMContentLoaded', function() {\n\t\t\t\tconst urlParams = new URLSearchParams(window.location.search);\n\t\t\t\tif (urlParams.has('error') || urlParams.has('success')) {\n\t\t\t\t\t// Clear URL parameters after 30 seconds\n\t\t\t\t\tsetTimeout(clearUrlParams, 30000);\n\t\t\t\t}\n\t\t\t});\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.App(props.AppProps).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
