// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package page

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/freekieb7/smauth/internal/account"
	"github.com/freekieb7/smauth/internal/web/ui/template/layout"
)

type DashboardProps struct {
	layout.AppProps
	User account.User
}

func Dashboard(props DashboardProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- Dashboard Cards --> <div class=\"row g-4\"><!-- Account Info Card --><div class=\"col-lg-6\"><div class=\"card border-0 h-100\" style=\"border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.08);\"><div class=\"card-body p-4\"><div class=\"d-flex align-items-center mb-3\"><div class=\"d-flex align-items-center justify-content-center me-3\" style=\"width: 48px; height: 48px; background: linear-gradient(135deg, #24E362 0%, #10B981 100%); border-radius: 12px;\"><i class=\"bi bi-person-badge text-white fs-5\"></i></div><h5 class=\"mb-0\" style=\"color: #0B1962; font-weight: 600;\">Account Information</h5></div><div class=\"space-y-3\"><div class=\"d-flex justify-content-between align-items-center py-2\" style=\"border-bottom: 1px solid #E5E7EB;\"><span style=\"color: #6B7280; font-size: 0.9rem;\">Email</span> <span style=\"color: #0B1962; font-weight: 500;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 30, Col: 74}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</span></div><div class=\"d-flex justify-content-between align-items-center py-2\" style=\"border-bottom: 1px solid #E5E7EB;\"><span style=\"color: #6B7280; font-size: 0.9rem;\">Role</span> <span style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("padding: 4px 12px; border-radius: 6px; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;", templ.KV("background: #FEF3C7; color: #D97706;", props.User.Role == account.RoleAdmin), templ.KV("background: #EBF8FF; color: #1E40AF;", props.User.Role == account.RoleUser))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 34, Col: 324}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Role.String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 35, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</span></div><div class=\"d-flex justify-content-between align-items-center py-2\" style=\"border-bottom: 1px solid #E5E7EB;\"><span style=\"color: #6B7280; font-size: 0.9rem;\">Email Status</span> <span style=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templruntime.SanitizeStyleAttributeValues("padding: 4px 12px; border-radius: 6px; font-size: 0.8rem; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;", templ.KV("background: #F0FDF4; color: #166534;", props.User.IsEmailVerified), templ.KV("background: #FEF2F2; color: #DC2626;", !props.User.IsEmailVerified))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 40, Col: 306}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.IsEmailVerified {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "Verified")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "Unverified")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</span></div><div class=\"d-flex justify-content-between align-items-center py-2\"><span style=\"color: #6B7280; font-size: 0.9rem;\">Member since</span> <span style=\"color: #0B1962; font-weight: 500; font-size: 0.9rem;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.CreatedAt.Format("January 2, 2006"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 50, Col: 123}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span></div></div></div></div></div><!-- Quick Actions Card --><div class=\"col-lg-6\"><div class=\"card border-0 h-100\" style=\"border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.08);\"><div class=\"card-body p-4\"><div class=\"d-flex align-items-center mb-3\"><div class=\"d-flex align-items-center justify-content-center me-3\" style=\"width: 48px; height: 48px; background: linear-gradient(135deg, #8B5CF6 0%, #7C3AED 100%); border-radius: 12px;\"><i class=\"bi bi-lightning text-white fs-5\"></i></div><h5 class=\"mb-0\" style=\"color: #0B1962; font-weight: 600;\">Quick Actions</h5></div><div class=\"d-grid gap-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.Role == account.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "<a href=\"/admin/users\" class=\"btn d-flex align-items-center justify-content-between p-3\" style=\"background: linear-gradient(135deg, #3B82F6 0%, #1D4ED8 100%); color: white; border: none; border-radius: 12px; text-decoration: none; font-weight: 500; transition: all 0.2s ease;\" onmouseover=\"this.style.transform='translateY(-2px)'; this.style.boxShadow='0 8px 25px rgba(59, 130, 246, 0.3)'\" onmouseout=\"this.style.transform='translateY(0)'; this.style.boxShadow='none'\"><div class=\"d-flex align-items-center\"><i class=\"bi bi-people me-3 fs-5\"></i><div><div style=\"font-size: 1rem; font-weight: 600;\">Manage Users</div><div style=\"font-size: 0.8rem; opacity: 0.9;\">View and edit user accounts</div></div></div><i class=\"bi bi-arrow-right fs-5\"></i></a>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div class=\"text-center py-4\"><div class=\"d-flex align-items-center justify-content-center mb-3\" style=\"width: 64px; height: 64px; background: linear-gradient(135deg, #24E362 0%, #10B981 100%); border-radius: 16px; margin: 0 auto;\"><i class=\"bi bi-check-circle text-white\" style=\"font-size: 1.5rem;\"></i></div><h6 style=\"color: #0B1962; font-weight: 600; margin-bottom: 8px;\">You're all set!</h6><p style=\"color: #6B7280; font-size: 0.9rem; margin-bottom: 0;\">Your account is active and ready to use.</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div></div></div></div><!-- Welcome Message --> <div class=\"row mt-4\"><div class=\"col-12\"><div class=\"card border-0\" style=\"border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.08); background: linear-gradient(135deg, #0B1962 0%, #1E40AF 100%);\"><div class=\"card-body p-4\"><div class=\"d-flex align-items-center\"><div class=\"d-flex align-items-center justify-content-center me-4\" style=\"width: 64px; height: 64px; background: rgba(255,255,255,0.15); border-radius: 16px;\"><i class=\"bi bi-person-circle text-white\" style=\"font-size: 2rem;\"></i></div><div><h3 class=\"mb-1\" style=\"color: white; font-weight: 700; font-size: 1.5rem;\">Welcome back, ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(props.User.Email)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/ui/template/page/dashboard.templ`, Line: 102, Col: 116}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "!</h3><p class=\"mb-0\" style=\"color: rgba(255,255,255,0.8); font-size: 1rem;\">You're successfully signed in to SMAuth.  ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if props.User.Role == account.RoleAdmin {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "Use the navigation to manage the system.")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "Your account is ready and secure.")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</p></div></div></div></div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.App(props.AppProps).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
